"""projects comments whitelist

Revision ID: 6c74591e1e2a
Revises: f8c545b8e9e4
Create Date: 2025-06-13 16:02:06.416096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c74591e1e2a'
down_revision = 'f8c545b8e9e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelist',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.add_column('blog_posts', sa.Column('project_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'project_id')
    op.drop_table('whitelist')
    # ### end Alembic commands ###
