"""create enusc_interanual

Revision ID: ddc03213bc39
Revises: 
Create Date: 2025-06-13 03:43:51.738590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc03213bc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enusc_interanual',
    sa.Column('id_unico', sa.BigInteger(), nullable=False),
    sa.Column('idr', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('region16', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('pad', sa.Integer(), nullable=True),
    sa.Column('padb', sa.Integer(), nullable=True),
    sa.Column('ped', sa.Integer(), nullable=True),
    sa.Column('rvi', sa.Integer(), nullable=True),
    sa.Column('rps', sa.Integer(), nullable=True),
    sa.Column('rfv', sa.Integer(), nullable=True),
    sa.Column('hur', sa.Integer(), nullable=True),
    sa.Column('les', sa.Integer(), nullable=True),
    sa.Column('prop_vehiculos', sa.Integer(), nullable=True),
    sa.Column('rdv', sa.Integer(), nullable=True),
    sa.Column('rddv', sa.Integer(), nullable=True),
    sa.Column('va_dc', sa.Integer(), nullable=True),
    sa.Column('vp_dc', sa.Integer(), nullable=True),
    sa.Column('rva_dc', sa.Integer(), nullable=True),
    sa.Column('fact_pers_2008_2019', sa.Float(), nullable=True),
    sa.Column('fact_hog_2008_2019', sa.Float(), nullable=True),
    sa.Column('varstrat', sa.BigInteger(), nullable=True),
    sa.Column('conglomerado', sa.BigInteger(), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('fact_pers_2019_2022', sa.Float(), nullable=True),
    sa.Column('fact_hog_2019_2022', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_unico')
    )
    op.create_index(op.f('ix_enusc_interanual_id_unico'), 'enusc_interanual', ['id_unico'], unique=False)
    op.create_index(op.f('ix_enusc_interanual_idr'), 'enusc_interanual', ['idr'], unique=False)
    op.create_index(op.f('ix_enusc_interanual_region'), 'enusc_interanual', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enusc_interanual_region'), table_name='enusc_interanual')
    op.drop_index(op.f('ix_enusc_interanual_idr'), table_name='enusc_interanual')
    op.drop_index(op.f('ix_enusc_interanual_id_unico'), table_name='enusc_interanual')
    op.drop_table('enusc_interanual')
    # ### end Alembic commands ###
