"""add tag to blog

Revision ID: f8c545b8e9e4
Revises: 20250613_01
Create Date: 2025-06-13 14:30:12.075809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c545b8e9e4'
down_revision = '20250613_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('tag', sa.String(length=120), nullable=True))
    op.alter_column('blog_posts', 'views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('blog_posts', 'tag')
    # ### end Alembic commands ###
